### PR TITLE
add more packages to requirements.txt

### PR DESCRIPTION
**Pull request by cnu**
add:
* psycopg
* reportlab
* qrcode

### CODE REVIEW

**Comment by ConfusedCrontab** [comment]
I noticed it and added today. But still its good to merge.

**Comment by cnu** [comment]
still it is hard to get the entire system running in 1 command. it requires pg running. you should create a docker-compose file which has all dependency services running.

**Comment by ConfusedCrontab** [comment]
I have committed the docker-compose.yml file. Check the commit history. But don't know why its showing up. Checked .gitignore too

**Comment by ConfusedCrontab** [comment]
Okay, found it. After accepting this PR, I too populated requirements.txt file. It resulted in a conflict. Now its resolved and pushed. docker-compose.yml file is available.

**Pull request merged**
